Vagrant.configure("2") do |config|

    config.vm.define "ubuntu11" do | ubuntu |
      ubuntu.vm.box = "ubuntu/bionic64"
      ubuntu.vm.network "private_network", ip: "192.168.56.11"
    end

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
  end

end
 